# name: NodeJS with Grunt

# on:
#   push:
#     branches: [ master ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.22]
    
#     steps:
#     - uses: actions/checkout@v2

#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}

#     - name: Install dependencies Build website
#       run: |
#         yarn install

#     - name: Build website
#       run: |
#         yarn build-pro
        
#     - name: Notify slack success
#       if: success()
#       env:
#         SLACK_BOT_TOKEN: xoxb-779312684481-2346459564545-9YBDzA98TLwxvXxMTi9orMRm
#       uses: voxmedia/github-action-slack-notify-build@v1
#       with:
#         channel: team_web_bds_project
#         status: BUILD SUCCESS `USERWEB` for commit name `${{ github.event.head_commit.message }}` from `${{ github.event.head_commit.author.name }}`
#         color: good
#     - name: Notify slack fail
#       if: failure()
#       env:
#         SLACK_BOT_TOKEN: xoxb-779312684481-2346459564545-9YBDzA98TLwxvXxMTi9orMRm
#       uses: voxmedia/github-action-slack-notify-build@v1
#       with:
#         channel: team_web_bds_project
#         status: BUILD FAILED `USERWEB` for commit name - `${{ github.event.head_commit.message }}` from `${{ github.event.head_commit.author.name }}`
#         color: danger
